name: Update CTFtime Rank

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-rank:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch CTFtime data
        run: python fetch_ranking.py > rank.tmp

      - name: Update README.md
        run: |
          sed -i '/<!-- CTFTIME_RANK_START -->/,/<!-- CTFTIME_RANK_END -->/{//!d}' README.md
          sed -i '/<!-- CTFTIME_RANK_START -->/r rank.tmp' README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Update CTFtime rank [skip ci]"
          git push
