name: Actualizar ranking en README

on:
  schedule:
    # Ejecuta diariamente a las 8:00 UTC (ajusta según necesites)
    - cron: '0 8 * * *'
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Necesario para hacer push después

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Ejecutar fetch_ranking.py y actualizar README
      run: |
        cd base
        OUTPUT=$(python fetch_ranking.py 2>&1)
        cd ..
        echo -e "\n## Ranking actualizado\n\n\`\`\`\n$OUTPUT\n\`\`\`" >> README.md
        
    - name: Commit y push de los cambios
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Actualización automática del ranking [skip ci]" || echo "No hay cambios que commitear"
        git push
